// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type FirstPageDocumentDataSlicesSlice = NavbarSlice;

/**
 * Content for first page documents
 */
interface FirstPageDocumentData {
	/**
	 * Slice Zone field in *first page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: first_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<FirstPageDocumentDataSlicesSlice>
	/**
	 * Meta Description field in *first page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: first_page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *first page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: first_page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *first page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: first_page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * first page document from Prismic
 *
 * - **API ID**: `first_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FirstPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<FirstPageDocumentData>,
	'first_page',
	Lang
>;

export type AllDocumentTypes = FirstPageDocument;

/**
 * Primary content in *Navbar → Items*
 */
export interface NavbarSliceDefaultItem {
	/**
	 * Navbar field in *Navbar → Items*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navbar.items[].navbar
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	navbar: prismic.SelectField<'1' | '2'>;
}

/**
 * Default variation for Navbar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavbarSliceDefault = prismic.SharedSliceVariation<
	'default',
	Record<string, never>,
	Simplify<NavbarSliceDefaultItem>
>;

/**
 * Slice variation for *Navbar*
 */
type NavbarSliceVariation = NavbarSliceDefault;

/**
 * Navbar Shared Slice
 *
 * - **API ID**: `navbar`
 * - **Description**: Navbar
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavbarSlice = prismic.SharedSlice<'navbar', NavbarSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			FirstPageDocument,
			FirstPageDocumentData,
			FirstPageDocumentDataSlicesSlice,
			AllDocumentTypes,
			NavbarSlice,
			NavbarSliceDefaultItem,
			NavbarSliceVariation,
			NavbarSliceDefault
		};
	}
}
